### ISSUE TITLE
【 Suggestion】Add gamemode and cheat lock

### ISSUE THREAD

**Issue by blood789** [mactso/HarderCheating#1]
【 Suggestion】Add gamemode and cheat lock
Difficulty Lock is very useful for modpack to increase the difficulty.
But player can use op command in server OR allow cheating when creating a single player game.

Can you add the following functions?
1、On the server, when the player is detected as an op, the op permission is deleted at any time. On the server, refuse to execute any commands.
2、When creating a single player game, players can only choose survival mode or hardcore mode, delete the choice of creative mode. Cheating is forced to close, and in the game, check whether cheating has started at regular intervals. When it is detected that a single player game has opened the cheating mode, it is forced to close.

In this way, no one can cheat with command，including op.....

**Comment by mactso** [comment]
Thanks!  Had my catalytic converter stolen so I am just seeing your suggestion now.   Thanks so much for your suggestion!
(if you own a car, look into getting an anti-theft protector for your converter-- this has been terrible).

Okay- So this would let a modpack designer prevent operators from changing the difficulty level.
One possibility would be to check the difficulty level and change it back to the correct value every second or so. 

I'm about to go on a trip but I'll look into this after my trip!
Thanks for the suggestions

However, keep in mind that a server operator could change the configuration values.

Two Guys,
MacTso
